# -*- coding: utf-8 -*-
"""DataSplit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kV0gvVy4cfdU14ndjv3rJ-qr7TJYJMUg
"""

from google.colab import drive
drive.mount('/content/drive')

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive/TFG/

!ls

#! unrar X /content/drive/MyDrive/TFG/RGB1.rar /content/drive/MyDrive/TFG/

"""# **Separación de la base de datos en train y test**"""

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('RGB1_split_v2.csv',delimiter=';')
df = df.dropna()
df.head(5)
X = pd.DataFrame(df, columns=['Sujeto','Ruta'])
y= pd.DataFrame(df, columns=['Accion'])
print(X)
#print(y)
train, test, = train_test_split(df,test_size=0.33, random_state=42)


train.to_csv("train2.csv", index=False)
test.to_csv("test2.csv", index=False)

